#!/usr/bin/env php
<?php

if ( file_exists( getcwd() . '/vendor/autoload.php' ) ) {
	require_once getcwd() . '/vendor/autoload.php';
} else {
	die( 'Vendor dependencies not found.' );
}

use Symfony\Component\Console\Application;

$application = new Application('Teak Documentation Generator');

$application->add(new \Teak\Console\ClassReferenceGenerator());
$application->add(new \Teak\Console\FunctionReferenceGenerator());
$application->add(new \Teak\Console\HookReferenceGenerator());

$application->run();
